services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: surveys
      POSTGRES_USER: survey
      POSTGRES_PASSWORD: survey
    ports:
      - "5555:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
